# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/TrailingWhitespace:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
Layout/SpaceAfterComma:
  Enabled: true
Layout/LeadingCommentSpace:
  Enabled: true
Layout/EmptyLineAfterMagicComment:
  Enabled: true
Layout/SpaceBeforeComma:
  Enabled: true

Style/StringLiterals:
  Enabled: false
Layout/SpaceAfterColon:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false